<?php

use Drupal\instance\DataCollector;
use Drupal\instance\DataTransmitter;

/**
 * When cron is run, send all data to our monitoring.
 *
 * @return void
 * @throws \GuzzleHttp\Exception\GuzzleException
 */
function instance_cron() {
  //ignore all local development environments - just in case
  if(preg_match('/^local\..*|.*\.local$|.*\.local\..*/', \Drupal::request()->getHost())) return;

  $dataCollector = new DataCollector();
  $data = $dataCollector->getData();

  try {
    $dataTransmitter = new DataTransmitter();
    $dataTransmitter->transmit($data);
  } catch (Exception $e) {
    \Drupal::logger('monitor')->error($e->getMessage());
  }
}
